### ISSUE TITLE
三列布局

### ISSUE THREAD

**Issue by liyann** [liyann/liyann.github.io#15]
#### 方法一：float法

注意点：三者排列顺序为左，右，中
左右中分别如下

```css
float:left,
float:right,
中间的width：auto
```

---
#### 方法二：absolute法

```css
.left:{
    position:absolute;
    left:0;
    top:0
}
.right{
    position:absolute;
    right:0;
    top:0;
}
.center{
    float:left;
    margin-left:left-length;
    margin-right:right-length;
}
```

#### 方法三：margin负值法完成三栏布局，代码如下
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>margin负值法完成三栏布局</title>
    <style type="text/css">

        html, body {
            margin: 0;
            height: 100%;
        }

        #main {
            width: 100%;
            float: left;
            height: 100%;
        }

        #main #body {
            background: #ffe6b8;
            margin: 0 210px;
            height: 100%;
        }

        #left {
            margin-left: -100%;
        }

        #right {
            margin-left: -200px;
        }

        #left, #right {
            float: left;
            width: 200px;
            height: 100%;
            background: teal;
        }
    </style>
</head>
<body>
<div id="main">
    <div id="body"></div>
</div>
<div id="left"></div>
<div id="right"></div>
</body>
</html>
```
